{
 "title": "nyc-dataset-prediction",
 "time": { "from": "2024-04-01T07:47:21.000Z", "to": "2024-04-30T10:25:37.000Z" },
 "panels": [
  {
   "title": "quantile values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", max_quantile_value FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}